disabled_rules:
  - trailing_whitespace
  - trailing_newline

line_length:
  warning: 105
  error: 120

identifier_name:
  min_length:
    warning: 0
    error: 0
  excluded:
    - id
    - URL
    - GlobalAPIKey

type_name:
  min_length:
    warning: 3
    error: 0
  excluded:
    - ID
    - URL

cyclomatic_complexity:
  warning: 15
  error: 20

function_body_length:
  warning: 100
  error: 150

file_length:
  warning: 500
  error: 1200

type_body_length:
  warning: 300
  error: 500
